data:
  augmentation: double
  data_path: data/tiles_all
meta:
  group: all_tiles_initial_exp
  name: cos_bs256_projpredsize128_pt
  outdir: ''
  project: solar-self-similarity
  resume: false
  tags: []
model:
  channels: 1
  checkpoint_location: None
  load_checkpoint: false
  prediction_size: 128
  projection_size: 128
  pretrain: True
testing:
  eval: false
training:
  batch_size: 256
  epochs: 10
  loss: cos
  lr: 0.1
  momentum_end: 1
  momentum_start: 0.99
  wd: 0.0001
